[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pygeoapi-"
version = "2020.0.0"
dependencies = [
  "httpx",
  "gidgethub[httpx]>4.0.0",
  "django>2.1; os_name != 'nt'",
  "django>2.0; os_name == 'nt'",
]